baseURL = 'https://spookyusers.github.io/blog/'
languageCode = 'en-us'
title = 'Kym Derriman'
theme = 'archie'
publishDir = "docs"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

